# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bfYcsB0kgUHTogY-C3rGFUh2SrN8zM6S
"""

import random

password_length = 12

characters = "abcde12345"

password = ""

for index in range(password_length):
    password = password + random.choice(characters)

print("Password generated: {}".format(password))


import random, string

password_length = 12

characters = string.ascii_letters + string.digits + string.punctuation

password = ""

for index in range(password_length):
    password = password + random.choice(characters)

print("Password generated: {}".format(password))

import random, string

password_length = int(input("Provide the password length: "))

characters = string.ascii_letters + string.digits + string.punctuation

password = ""

for index in range(password_length):
    password = password + random.choice(characters)

print("Password generated: {}".format(password))

import random, string

number_of_passwords = int(input("How many passwords do you want to generate? "))
password_length = int(input("Provide the password length: "))

characters = string.ascii_letters + string.digits + string.punctuation

for password_index in range(number_of_passwords):
    password = ""

    for index in range(password_length):
        password = password + random.choice(characters)

    print("Password {} generated: {}".format(password_index, password))

    import random, string

number_of_passwords = int(input("How many passwords do you want to generate? "))
password_length = int(input("Provide the password length: "))

characters = string.ascii_letters + string.digits + string.punctuation

for password_index in range(number_of_passwords):
    password = ""

    for index in range(password_length):
        password = password + random.choice(characters)

    print("Password {} generated: {}".format(password_index, password))